image: golang:latest
stages:
  - build
  - deploy

build:
  stage: build
  script:
    - echo {$CI_COMMIT_TAG}
    - cp `pwd` /go/src/logAnalyser -Rf
    - cd /go/src/logAnalyser
    - go get github.com/droundy/goopt
    - go get github.com/satyrius/gonx
    - go build -v

deploy:
  stage: deploy
  script:
    - curl -O http://devtools.qiniu.com/qshell-v2.0.6.zip
    - unzip qshell-v2.0.6.zip
    - mv qshell_linux_amd64 qshell
    - chmod a+x qshell
    - ./qshell -m account $QINIU_ACCESS_KEY $QIUNIU_SECRET_KEY
    - ./qshell -m fput download-devtest nginx-log-analyser-v{$CI_COMMIT_TAG} ./logAnalyser true
  only:
    - tags